---
title: "Homework 9"
author:
- Alicja Dutkiewicz - s2530856
- Irina Gurewitsch - s2621258
- João Esteves - s2679663
date: "13/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library('maps'); 
library('geosphere'); 
library(igraph);
```

## Exercise 1

```{r}
CTMC <- function(G, lambda) # Simulate Continuous Time Markov Chain 
{
  # Input: G (in current state), contagiousness lambda
  # Output: G (state after event), DeltaT: time interval until event
  qi <- rep(0.0, vcount(G));
  qii = 0;
  alive <- FALSE
  for (j in 1:vcount(G))
  {
    if (V(G)$state[j] == 0)
    {
      # count incoming flights from infected neighbors;
      v=0;
      for (nb in neighbors(G,V(G)[j],mode=c("in")) ) 
        if (V(G)$state[nb] ==1 ) v <- v+1;
      qi[j] <- lambda * v; # compute rate q_ij
      if (qi[j] > 0) alive <- TRUE;  # Process is still alive
    }
  }
  qii = sum(qi)  # Rate of leaving the current state i
  
  if (alive)
  {
    # Compute exponential distribution, rate qii
    DeltaT <- rexp(1,qii) 
    # Update graph, select event proportional to rate
    sumprob = 0;
    u <- runif(1);
    for (j in 1:vcount(G))
    {
      previous_sumprob = sumprob;
      if (V(G)$state[j] == 0 && qi[j] != 0)
      {sumprob = sumprob + qi[j]/qii;}
      if (previous_sumprob < u && u <= sumprob) 
        V(G)$state[j]=1;}   # vertex j gets infected
  }
  else
    DeltaT <- Inf; # Infinity; Signals that absorbing state is reached
  
  return(list(first=G, second=DeltaT))
}
```

```{r}
# Load the data (adapt the pathnames)
#setwd("./data") # Adapt this to your directory path
airports <- read.csv("Dataset3-Airlines-NODES.csv", header=TRUE) 
flights <- read.csv("Dataset3-Airlines-EDGES.csv", header=TRUE, 
                    as.is=TRUE)
# Select only the big airports
tab <- table(flights$Source)
big.id <- names(tab)[tab>10]
airports <- airports[airports$ID %in% big.id,]
flights  <- flights[flights$Source %in% big.id & 
                      flights$Target %in% big.id, ]
# Plot map of the USA
# In some cases this needs to be added, here: dev.off();   
# map("state", col="grey50", fill=TRUE, bg="blue", lwd=0.1)
# Plot orange edges, eavier edges will be lighter in color.
# col.1 <- adjustcolor("orange red", alpha=0.4)
# col.2 <- adjustcolor("orange", alpha=0.4)
# edge.pal <- colorRampPalette(c(col.1, col.2), alpha = TRUE)
# edge.col <- edge.pal(100)
edgelist = c();
for(i in 1:nrow(flights))  {   # Plot edges
  node1 <- airports[airports$ID == flights[i,]$Source,]
  node2 <- airports[airports$ID == flights[i,]$Target,]
  # arc <- gcIntermediate( 
  #   c(node1[1,]$longitude, 
  #     node1[1,]$latitude), 
  #   c(node2[1,]$longitude, 
  #     node2[1,]$latitude), 
  #   n=1000, addStartEnd=TRUE )
  edge.ind <- round(100*flights[i,]$Freq / max(flights$Freq))
  # lines(arc, col=edge.col[edge.ind], lwd=edge.ind/30)
}  
# ... now start simulation 
colors <- c('purple', 'blue', 'green', 'red', 'pink')
plot(1, xlab="Time", ylab="Nodes Infected", xlim=c(0,5000), ylim=c(0,nrow(airports)))
for (r in 1:5) {
  set.seed(r)
  # initialize edges
  for(i in 1:nrow(flights)) {   
    i1 <- which(airports$ID == flights[i,]$Source)
    i2 <- which(airports$ID == flights[i,]$Target)
    edgelist <- c(edgelist, i1); edgelist <- c(edgelist, i2);}
  G <- graph(edgelist);
  
  # start the simulator from initial state (1st node infected)
  Time = 0; 
  V(G)$state <- 
    c(1,0,0, 0,0,0, 0,0,0,
      0,0,0, 0,0,0, 0,0,0,
      0,0,0, 0,0,0, 0,0,0)
  DeltaT = 0
  points(x=0, y=1, pch=19, col=colors[r])
  while (Time < 20000 & DeltaT != Inf) {
    L <-CTMC(G,0.001); # simulate next event, lambda=0.001
    DeltaT <- L$second; 
    G <- L$first;
    if (DeltaT != Inf)
    {
      Time = Time + DeltaT;
      InfectedNodes <- sum(V(G)$state)
      points(x=Time, y=InfectedNodes, pch=19, col=colors[r])
    } 
  };
  cat('Total Time:', Time, '\n')
}
```
## Exercise 2

```{r}
CTMC_SIS <- function(G, lambda) # Continuous Time Markov Chain
{
  # Input: G (in current state), contagiousness lambda
  # Output: G (state after event), DeltaT: holding time
  qi <- rep(0.0, vcount(G));
  qii = 0;
  recov <- rep(0.0, vcount(G));
  alive <- FALSE
  for (j in 1:vcount(G))
  {
    if (V(G)$state[j] == 0)
    {
      # count incoming edges from infected neighbors;
      v=0;
      for (nb in neighbors(G,V(G)[j],mode=c("in")) )
        if (V(G)$state[nb] ==1 ) v <- v+1;
        qi[j] <- lambda * v; # compute rate q_ij
        if (qi[j] > 0) alive <- TRUE;# Process is still alive
    }
    else 
    {
      recov[j] = 50.0 * lambda / airports$Visits[j];
    }
    #    else if (V(G)$state[j] == 1)
    # {
    #     qi[j] <- 50.0*lambda/airports$Visits[j]; # rate q_ij
    #     if (qi[j] > 0) alive <- TRUE;# Process is still alive
    # }
  }
  qii = sum(qi)+sum(recov);# Rate of leaving the current state i
  recov_sum = sum(recov);
  if (alive)
  {
    # Compute exponential distribution, rate qii
    DeltaT <- rexp(1,qii)
    # Update graph, select event proportional to rate
    sumprob = 0;
    u <- runif(1);
    for (j in 1:vcount(G))
    {
      previous_sumprob = sumprob;
      if (V(G)$state[j] == 0 && qi[j] != 0)
      {sumprob = sumprob + qi[j]/qii;}
      else if (V(G)$state[j] == 1)
      {
        sumprob = sumprob + recov[j]/qii;
      }
      if (previous_sumprob < u && u <= sumprob)
        {if (V(G)$state[j] == 0)
          {V(G)$state[j]=1;}
        else
          {V(G)$state[j]=0;}
        }
      }
    # vertex j gets infected
    
    # sumprob_recov = 0;   
    # for (j in 1:vcount(G))
    # {
    #   previous_sumprob_recov = sumprob_recov;
    #   if (V(G)$state[j] == 1)
    #   {sumprob_recov = sumprob_recov + recov[j]/recov_sum;}
    #   if (previous_sumprob_recov < u && u <= sumprob_recov)
    #     V(G)$state[j]=0;
    # }
  }
  else
    DeltaT <- Inf; # Infinity; Absorbing state is reached
  return(list(first=G, second=DeltaT))
}

# ... now start simulation 
colors <- c('purple', 'blue', 'green', 'red', 'pink')
plot(1, xlab="Time", ylab="Nodes Infected", xlim=c(0,5000), ylim=c(0,nrow(airports)))
for (r in 1:5) {
  set.seed(r)
  # initialize edges
  for(i in 1:nrow(flights)) {   
    i1 <- which(airports$ID == flights[i,]$Source)
    i2 <- which(airports$ID == flights[i,]$Target)
    edgelist <- c(edgelist, i1); edgelist <- c(edgelist, i2);}
  G <- graph(edgelist);
  
  # start the simulator from initial state (1st node infected)
  Time = 0; 
  V(G)$state <- c(1,1,1, 1,1,1, 0,0,0, 0,0,0, 0,0,0, 0,0,0, 0,0,0, 0,0,0, 0,0,0)
    
  DeltaT = 0
  points(x=0, y=1, pch=19, col=colors[r])
  while (Time < 2000 & DeltaT != Inf) {
    L <-CTMC_SIS(G,0.001); # simulate next event, lambda=0.001
    DeltaT <- L$second; 
    G <- L$first;
    if (DeltaT != Inf)
    {
      Time = Time + DeltaT;
      InfectedNodes <- sum(V(G)$state)
      points(x=Time, y=InfectedNodes, pch=19, col=colors[r])
    } 
  };
  cat('Total Time:', Time, '\n')
}

```